### ISSUE TITLE
Missing translation for "Impersonate" in de_DE.js

### ISSUE THREAD

**Issue by daCaPo** [nextcloud/impersonate#115]
In the file `l10n/de_DE.js` ("formal German"), the translation string for "Impersonate" in line 7 should read "Nachahmen" as in `de.js`.

**Comment by blizzz** [comment]
I think translators did not translate it as it is the app name. Translations are handled in [Transifex](https://www.transifex.com/nextcloud/nextcloud/impersonate/) and coordinate in the [forums](https://help.nextcloud.com/c/translations/23).

**Comment by daCaPo** [comment]
Sorry, this is not the app name. This is the string displayed in the context menu. In "de.js", it is correctly translated.

**Comment by blizzz** [comment]
> Sorry, this is not the app name. This is the string displayed in the context menu. In "de.js", it is correctly translated.

OK. Please suggest a change at transifex.
