### ISSUE TITLE
Cannot Clear Impersonated User's Notifications

### ISSUE THREAD

**Issue by Prog1563** [nextcloud/impersonate#116]
NC 19.0.3
Impersonate: 1.6.1

When impersonating a user, it is impossible to clear their notifications. When trying to clear the notifications, a toast pops up that reads "Failed to dismiss notification".

When diving into the web console, the following can be found: "DELETE https://[SERVER_URL]/ocs/v2.php/apps/notifications/api/v2/notifications/92 **403**" Where [SERVER_URL] is my server's address.

No errors are logged to the Nextcloud log.

**Comment by blizzz** [comment]
I am not sure this is a bad thing per se. Is there a valid reason to dismiss someone else's notifications?

**Comment by Prog1563** [comment]
The account that I was trying to clear the notifications of was a service account that was only used to have a sync client sync pictures to a TV. This use case has since been removed. The reason we were using impersonate was because we forgot the password for the account and didn't want to break things by changing it. Lol
