### ISSUE TITLE
Transparency Controls (Notifications) for Impersonate app

### ISSUE THREAD

**Issue by jpubb** [nextcloud/impersonate#119]
(enhancement) request....

The “Impersonate” app from admin perspective is a life saver.

It would be great if there was an option to add usage transparency feature so both users and others interested (i.e. CEO, Security Officer, etc.) may know when Impersonate was used by an admin.

So I would suggest the following enhancements as admin options:

**IMPERSONATION TRANSPARENCY CONTROL OPTIONS:**
[ ] Require “Reason: __________” comment by admin when using impersonate.
[ ] Create entry in activity log that impersonate was used (i.e. "$impersonating_admin has impersonated $impersonated_user")
[ ] Add Nextcloud notification for user when impersonated (only clearable by the impersonated user)
[ ] Email user when impersonated (w/reason if required in previous option)
[ ] Notify these additional user(s)/group(s) when Impersonation is used: [user/group selection]
[ ] Also notify the users/group above by email and notification when ANY of these impersonation options are altered.

I think these features would really round out the app and make executive staff and users comfortable with admins being able to “impersonate” them and other users on the system.

Thanks for considering

**Comment by jpubb** [comment]
I also split them up as issues  #120 #121 #122  if someone will work opt to work on them in stages.

**Comment by blizzz** [comment]
> I also split them up as issues #120 #121 #122 if someone will opt to work on them in stages.

thanks. closing this one hence.
