### ISSUE TITLE
Impersonating gives internal server error, then logs in a second time with same user

### ISSUE THREAD

**Issue by andyboeh** [nextcloud/impersonate#12]
When trying to impersonate another user (it doesn't matter which one) I first get an Internal Server Error (logfile below), then I'm logged in a second time as my original user. If I log out once, I am back at my original user (again) and need to log out a second time to really log out.

I have user_saml as user backend installed, I do not use LDAP nor any other backend. NextCloud 12.0.2, PHP 7.1, Apache 2.4, Linux host.

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_authtoken`(`uid`,`login_name`,`name`,`token`,`type`,`remember`,`last_activity`) VALUES(?,?,?,?,?,?,?)' with params ["USER@DOMAIN", "USER@DOMAIN", "Mozilla\/5.0 (X11; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0", "TOKEN_HERE", 0, 0, 1502990275]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'TOKEN_HERE' for key 'authtoken_token_index'

    /var/www/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/www/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)
    /var/www/cloud/lib/public/AppFramework/Db/Mapper.php - line 247: Doctrine\DBAL\Statement->execute()
    /var/www/cloud/lib/public/AppFramework/Db/Mapper.php - line 125: OCP\AppFramework\Db\Mapper->execute('INSERT INTO `*P...', Array)
    /var/www/cloud/lib/private/Authentication/Token/DefaultTokenProvider.php - line 97: OCP\AppFramework\Db\Mapper->insert(Object(OC\Authentication\Token\DefaultToken))
    /var/www/cloud/lib/private/User/Session.php - line 610: OC\Authentication\Token\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)
    /var/www/cloud/lib/private/legacy/user.php - line 205: OC\User\Session->createSessionToken(Object(OC\AppFramework\Http\Request), 'USER@DOMAIN', 'USER@DOMAIN')
    /var/www/cloud/lib/private/legacy/user.php - line 238: OC_User loginWithApache(Object(OCA\User_SAML\UserBackend))
    /var/www/cloud/apps/user_saml/appinfo/app.php - line 50: OC_User handleApacheAuth()
    /var/www/cloud/lib/private/legacy/app.php - line 209: require_once('/var/www/cloud....')
    /var/www/cloud/lib/private/legacy/app.php - line 149: OC_App requireAppFile('user_saml')
    /var/www/cloud/lib/private/legacy/app.php - line 124: OC_App loadApp('user_saml')
    /var/www/cloud/lib/base.php - line 982: OC_App loadApps(Array)
    /var/www/cloud/index.php - line 48: OC handleRequest()
    {main}
```

**Comment by e-alfred** [comment]
The problem still exists with 12.0.3. I do not use any external authentication system.

I get this message:

`
{"reqId":"BnESYhlFd6HwDGG8UoyX","level":3,"time":"2017-10-02T14:19:31+00:00","remoteAddr":"1.1.1.1","user":"user","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.102 Safari\/537.36 Vivaldi\/1.94.971.8","version":"12.0.3.3"}`

**Comment by fiforms** [comment]
I have exactly the same problem with impersonate, also with user_saml backend. Any thoughts?

**Comment by andyboeh** [comment]
It works now for me on NC17. I'm closing it.
