### ISSUE TITLE
iPhone: "Impersonate" not clickable

### ISSUE THREAD

**Issue by lars-sh** [nextcloud/impersonate#124]
### Steps to reproduce
1. Open up the users overview using an iPhone Browser (such as Edge or Safari).
2. Tap the three dots beneath one of the users.
3. Try clicking "Impersonate".

### Expected behaviour
Nextcloud asks if I really want to impersonate that user.

### Actual behaviour
The three-dots-menu closes and nothing happens at all.

## Server configuration detail

**Operating system:** Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (fpm-fcgi)

**Database:** mysql 10.3.25

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, using Nextcloud for some years

**Where did you install Nextcloud from:** manual installation, downloaded ZIP from official website

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - apporder: 0.11.0
 - bookmarks: 4.0.5
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.2
 - contactsinteraction: 1.1.0
 - dav: 1.16.1
 - deck: 1.2.2
 - extract: 1.2.5
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_antivirus: 3.0.0
 - files_linkeditor: 1.1.2
 - files_markdown: 2.3.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.0.4
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.7.0
 - maps: 0.1.8
 - metadata: 0.12.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - polls: 1.6.2
 - previewgenerator: 3.0.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - ransomware_protection: 1.8.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.10
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.3
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - viewer: 1.4.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - dashboard
 - encryption
 - files_external
 - notes
 - ransomware_detection
 - sharerenamer
 - tasks
 - user_ldap
 - user_status
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "secret": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "enable_certificate_management": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud. ***REMOVED SENSITIVE VALUE***.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "version": "20.0.2.2",
    "dbtype": "mysql",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "installed": true,
    "default_language": "de",
    "overwritehost": "cloud.knickrehm.net",
    "overwriteprotocol": "https",
    "overwritewebroot": "\/",
    "overwrite.cli.url": "https:\/\/cloud. ***REMOVED SENSITIVE VALUE***.net",
    "htaccess.RewriteBase": "\/",
    "enable_previews": true,
    "maintenance": false,
    "singleuser": false,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "trashbin_retention_obligation": "disabled",
    "versions_retention_obligation": "disabled",
    "filesystem_check_changes": 1,
    "loglevel": 2,
    "logfile": "\/mnt\/data\/logs\/cloud\/today.log",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpport": "25",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "apps_paths": [
        {
            "path": "\/***REMOVED SENSITIVE VALUE***\/cloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/***REMOVED SENSITIVE VALUE***\/cloud\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 EdgiOS/45.11.1 Mobile/15E148 Safari/605.1.15

**Operating system:** iOS 14.2

**Comment by blizzz** [comment]
I don't suppose you get any logs out of the browser there?

**Comment by lars-sh** [comment]
At least I'm not aware how to accomplish that. Isn't there somebody out there, who has an iPhone, can do so and is able to reproduce that?

**Comment by blizzz** [comment]
Does any other function in that menu work?

**Comment by lars-sh** [comment]
None of the menu entries can be reached. It seems, the menu is closed on tap-on-screen, while actions should be activated when releasing the screen, so the menu is closed prior handling the tap action on the menu entry. Instead the underlying list item is selected.

Is that context menu somewhat different from the others? As the files context menu and others work the way I expect them to work.

The problem occurs on my the iPhone 8 and others around myself (e.g. the iPhone 8 of my wife), in Safari Mobile, Firefox on iPhone, Edge on iPhone and with two separate and up-to-date Nextcloud installations.

**Comment by blizzz** [comment]
@skjnldsv ^ this is then either users page or nextcloud-vue that is probably not working on the apple phone. what do you think?

**Comment by skjnldsv** [comment]
No clue. Most likely something to ask on the vue channel

**Comment by blizzz** [comment]
> No clue. Most likely something to ask on the vue channel

Would you do that?

**Comment by HolyMacarony** [comment]
It's still the very same problem for android. This makes it unusable on mobile devices.

**Comment by lars-sh** [comment]
This does not seem to be related to the Impersonate app, but is a general problem, which is decribed at https://github.com/nextcloud/server/issues/21260, too. Therefore I close this as kinda duplicate and continue over there.
