### ISSUE TITLE
Could not validate CRL signature

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/impersonate#126]
@blizzz 

Cannot upgrade on 1.8.0 on NC21 Beta7 because of invalid CRL-Signature

**Comment by Lars1963** [comment]
Maybe related to:
https://github.com/nextcloud/server/issues/25303

**Comment by blizzz** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/25214 and the next pre-release.
