### ISSUE TITLE
Impersonate not working after update NC to 20.0.4

### ISSUE THREAD

**Issue by ThomasAndreini** [nextcloud/impersonate#128]
After updating Nextcloud to version 20.0.4 on Ubuntu server I can no longer find the "impersonate" item in the three-dot menu. The application is installed, I tried to remove and reinstall it, but as an administrator I can no longer use it.
The admin user is in the admin group, I tried to make him an administrator of the other groups as well and to insert the other groups in the impersonate user list, nothing has changed.

**Comment by schniepp** [comment]
I am on 20.0.9, and it's also not working...

**Comment by informatico-madrid** [comment]
+1, Same here, Update to +20 Impersonate menu option of user is not available any more.

**Comment by mMuck** [comment]
This happened to me (or I realized it) too @ v22.2.3
I disabled the app and re-enabled it within the app menu. The impersonate menu option re-appeared - works normal.

**Comment by mehdibo** [comment]
Using Nextcloud 22.2.5
First time using this app I can't seem to find the impersonate button, reinstalling did not solve the problem for me

**Comment by punkyard** [comment]
total log out after impersonate, instead of going back to admin account

**Comment by solracsf** [comment]
Closing as fixed. Report back if not working in recent versions (23+).
