### ISSUE TITLE
Nextcloud 25 Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/impersonate#161]

**Comment by neufeind** [comment]
Compatibility version is already raised, but we're missing a release it seems? Just stumbled over this, since now Nextcloud 25 is actively rolled-out and this (as well as other plugins) are missing a compatible release on apps.nextcloud.com.

**Comment by andyxheli** [comment]
https://github.com/nextcloud/impersonate/commit/34b43865aa383afadc3fca7ce86c4ff7a25e923b

**Comment by nursoda** [comment]
25.0.1 is out, please update. If I "allow untested", Impersonate works perfectly fine for me on NC25.

**Comment by resposit** [comment]
Hi, still waiting for the update....

**Comment by ksteinb** [comment]
I also wait for the update

**Comment by GitBaer** [comment]
When will it be released?

**Comment by pgassmann** [comment]
Nextcloud 25.0.2 is now recommended on the stable channel. 

@nickvergessen can you provide some transparency why this official app by Nextcloud GmbH is not released for the current stable version?

**Comment by BurtGummer** [comment]
I think this functionality belongs in the main version.

**Comment by livier** [comment]
> I think this functionality belongs in the main version.

Impersonate would be obsolete ? 
and any Nextcloud instance would permit it without this app ? 

Did not found how to make the same thing without it. 
Say how please ...

**Comment by christianlupus** [comment]
As far as I understood him, this functionality **should** be part of the core instead of an app. It is not yet so. But it is a tool for the admins to help in case a user has a problem.

**Comment by livier** [comment]
ok, excuse my frenchglish ... should / would ... 
I know it's for admins, I use it for that. And I'll "allow untested" next time I'll need it if not updated before. 
Not sure it's a good idea to make it part off the core. Mayde some admins do not need it or it could be forbidden by some  security policy ...

**Comment by DriedPlumber** [comment]
This should be part of the core instead of an app. 
Next time I will not update NextCloud as long as the apps are not updated...

**Comment by nursoda** [comment]
Yes, checking whether all apps that are important to you are supported prior to upgrading is a good idea. The web updater even tells you what would be "incompatible" afterwards.

That said, for most small apps, a simple "allow untested" will do as breaking changes are rather rare.

To even catch these, you should run a test instance, e.g. in a subfolder. There you may easily test without sacrificing your production data.

But…such rants and infos should rather be posted in the forum. If anyone feels that it needs a discussion thread, please open one there and link it here.

**Comment by jmigual** [comment]
@blizzz would it be possible to add a release of this app for Nextcloud 25 in the Nextcloud store?

**Comment by guillemsuetta** [comment]
> @blizzz would it be possible to add a release of this app for Nextcloud 25 in the Nextcloud store?

Any time estimate when the release of the app for Nextcloud 25 will be on the Nextcloud store?

**Comment by dirdi** [comment]
I suspect there could be a bug and one does not want to release a new version until this bug was fixed.

**Comment by beyercenter** [comment]
no one assigned, so no one will do anything :-(

**Comment by livier** [comment]
[ this app is following a branched pattern. There is a stable branch for each Nextcloud major version.
It's just missing a release from there](https://github.com/nextcloud/impersonate/commit/34b43865aa383afadc3fca7ce86c4ff7a25e923b#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9e)
This app seem ready for Nextcloud 25 and 26 ! 

Who can release ? 
If nobody available for that, can anybody check if there are changes between releases 1.11 ; 1.12 and 1.13, and if this changes could damage something ? (I'm not used to using GitHub to be able to do this). 
We would be safe for  "allow untested"

**Comment by canonex** [comment]
Yes, this plugin is very handy:
I'm still on Nextcloud 24 because of this missing update.

**Comment by R0Wi** [comment]
> [ this app is following a branched pattern. There is a stable branch for each Nextcloud major version. It's just missing a release from there](https://github.com/nextcloud/impersonate/commit/34b43865aa383afadc3fca7ce86c4ff7a25e923b#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9e) This app seem ready for Nextcloud 25 and 26 !
> 
> Who can release ? If nobody available for that, can anybody check if there are changes between releases 1.11 ; 1.12 and 1.13, and if this changes could damage something ? (I'm not used to using GitHub to be able to do this). We would be safe for "allow untested"

Can confirm that the code of [`stable25`](https://github.com/nextcloud/impersonate/tree/stable25) works in a NC25 instance. If you have a look at the [diff](https://github.com/nextcloud/impersonate/compare/v1.11.0...stable25) between the latest release `v1.11` (which is for NC24) and the current `stable25`, you'll see that only the app metadata, CI/CD related stuff and many localizations have changed. So no "real" code changes here (which is expected, I'm also an app developer and I did not need to change much to make my app compatible with NC25). What you could do is either activate `v1.11.0` from the NC app store as "enable untested app" or download the app yourself:

```bash
cd <YOUR_NC_ROOT>/apps
wget https://github.com/nextcloud/impersonate/archive/refs/heads/stable25.zip
unzip stable25.zip
mv impersonate-stable25 impersonate
# Change this to match the user running your webserver
chown -R www-data:www-data impersonate
```

I did the latter and it all works as expected. Just one thing to note: the UI has changed a little bit so you can access the impersonate-button through the three-dots menu now (not like shown in the docs screenshot)

![image](https://user-images.githubusercontent.com/19730957/220297392-93e03df1-b44f-4a47-9bf8-f3abfecaed87.png)

**Comment by blizzz** [comment]
was published, also against 26.
