### ISSUE TITLE
Add: Emitter event so that other apps know about impersonate

### ISSUE THREAD

**Issue by the-djmaze** [nextcloud/impersonate#179]
My app has a login system and users have an issue when impersonating, the login doesn't logout.
https://github.com/the-djmaze/snappymail/issues/561

I've tried to create a workaround but that has issues with storing data in session (NC25 might solve this).
https://github.com/nextcloud/server/issues/34935

However, i think it would be better to have an event to listen to for a much better approach.
Can you add an emit() like:

https://github.com/nextcloud/impersonate/blob/7690e011abadc8070439e336fd107b768e1afd08/lib/Controller/SettingsController.php#L157
```php
		$this->userSession->getManager()->emit('\OC\User', 'impersonate', [$currentUser, $user])
		$this->userSession->setUser($user);
```

https://github.com/nextcloud/impersonate/blob/7690e011abadc8070439e336fd107b768e1afd08/lib/Controller/LogoutController.php#L63
```php
		$this->userSession->getManager()->emit('\OC\User', 'impersonate', [$this->userSession->getUser(), $user])
		$this->userSession->setUser($user);
```

**Comment by blizzz** [comment]
should be a typed event nowadays, but generally a PR implemeted this would be accepted.

As a workaround, perhaps checking whether `session->get('oldUserId')(from OCP\ISession)` is set could already help.

**Comment by the-djmaze** [comment]
> As a workaround, perhaps checking whether `$session->get('oldUserId')` (from OCP\ISession) is set could already help.

That has an issue.
1. Login Nextcloud
2. SnappyMail login IMAP
3. Impersonate
4. if (oldUserId) SnappyMail->logout()
5. Login SnappyMail manually
6. if (oldUserId) SnappyMail->logout()

Step 5 - 6 will then be a repeat, so there must be some kind of permanent check.
1. SnappyMail keeps track of current IUser
2. Or just listen to events

**Comment by the-djmaze** [comment]
WIP at #180

**Comment by criegerde** [comment]
I was asked for #[linking](https://github.com/nextcloud/server/issues/53906#issuecomment-3062724877) this issue by you colleague.
[https://github.com/nextcloud/server/issues/53906#issuecomment-3062724877](url)
