### ISSUE TITLE
Too many users in the list

### ISSUE THREAD

**Issue by malimarwa** [nextcloud/impersonate#188]
we want to use the impersonate plugin in Nextcloud, but we had a difficulty when selecting a user, because we have 15,000 users, and we don't have the means to do a search.
Can you help us to add search bar in the selection of users ?

**Comment by solracsf** [comment]
What do you mean by
> we don't have the means to do a search
? There is the search icon on the top bar.

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
