### ISSUE TITLE
NC13b3: Logout impersonated session leads to main session being logged out

### ISSUE THREAD

**Issue by nursoda** [nextcloud/impersonate#22]
Steps to reproduce:
- Install NC13b3
- Login as admin user (in my case using TOTP)
- Activate Impersonate App
- Impersonate an existing user
- Log out impersonated user

Expected:
- Be back in main (admin) session

Actual
- Back to Login screen (completely logged out)

**Comment by RailsViceRoads** [comment]
I have the same behaviour with NC 13.0.0.14 and Impersonate 1.0.2.
But logout works as expected, if admin user **and** "impersonated user" member of group "admin".

**Comment by nursoda** [comment]
Oh, for me, the issue is solved. Don't know when it changed but latest since release, impersonate works fine for me again. I only have non-admin users I impersonate, so for me, it's now:

- login as admin
- impersonalte non-admin-user
- do things
- logout
- I'm back as admin

I would close it but I'm not sure since @RailsViceRoads seems to have issues.

**Comment by RailsViceRoads** [comment]
Perhaps I can provide some data (NC-log, browser console log, etc.). But I need some guidance what for informations are needet and how I can capture it.

**Comment by nursoda** [comment]
I suggest you open a new bug. There, you get a template that explains how to gather data and which. Then, close this bug und link to it.

**Comment by RailsViceRoads** [comment]
Ok. I opened [issue #31](https://github.com/nextcloud/impersonate/issues/31) now.
