### ISSUE TITLE
Doesn't seem to work for group admins

### ISSUE THREAD

**Issue by forlornidealist** [nextcloud/impersonate#223]
I see that the ability to let group admins to use the impersonate feature was added long ago in #25, however I do not see the option for impersonate when logged in as a group admin like I do when logged in as a general administrator. Is that feature is not compatible with the current version of Nextcloud, or am I missing something?

![Screenshot_20230610_021858](https://github.com/nextcloud/impersonate/assets/7444293/e8f2c7e6-9410-4de0-8135-b89be129d4a2)

**Comment by akha666** [comment]
+1
I don't the Impersonate icon for the Group Admins 
Nextcloud v26.0.2

**Comment by pjrobertson** [comment]
I am also experiencing this issue. Group admins cannot 'impersonate' their group users. Right now only super users can do it

**Comment by blizzz** [comment]
Group admins are not allowed to impersonate by default, only admins are. You can add group admins into a different group, and allow this group to impersonate in Admin Settings –> Additional Settings.

**Comment by pjrobertson** [comment]
@blizzz  - that is exactly what I have done, and it does not work. Here are the steps to reproduce:

1. Create a group called 'User admin' (used for impersonate admin privileges) and a group called 'My Group' (used to decide who to impersonate)
2. Add user A to the group 'User admin', and make user A an admin of group 'My Group'
3. Login as user A
4. Go to the 'Users' page, and click the 'My Group' group.
5. Try to impersonate a user in 'My Group'
6. Note that the 'impersonate' option is not there

Can this issue please be re-opened?

**Comment by blizzz** [comment]
I cannot reproduce your issue on 27. By chance, you did not limit the app to certain groups on the app settings, https://your.nc.srv/index.php/settings/apps/installed/impersonate ?

**Comment by pjrobertson** [comment]
I just checked and no - it is not limited to groups:

<img width="1130" alt="Screen Region 2023-11-13 at 21 07 57" src="https://github.com/nextcloud/impersonate/assets/150431/0066e553-343f-4ff7-b9a9-e4b5837608e2">

Oh wait - I double checked my Impersonate settings in Admin settings > Additional settings and the 'User admin' group had somehow been removed. Adding it in again and I can confirm everything works.

I appreciate the help debugging blizzz, thanks! 👍
