### ISSUE TITLE
Changelog is not up-to-date with releases

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/impersonate#224]
The [`CHANGELOG.md`](https://github.com/nextcloud/impersonate/blob/master/CHANGELOG.md) does not contain all [releases](https://github.com/nextcloud/impersonate/releases) and is not up-to-date.  
There seems to be only one release in there. Newer and older ones are missing.

And it also doesn't adhere to:
- https://nextcloudappstore.readthedocs.io/en/latest/developer.html?highlight=changelog#changelog
- https://keepachangelog.com/

So the "Changelog" tab in the Nextcloud admin app interface stays empty when opening the details of the app.

**Comment by blizzz** [comment]
> The [CHANGELOG.md](https://github.com/nextcloud/impersonate/blob/master/CHANGELOG.md) does not contain all [releases](https://github.com/nextcloud/impersonate/releases) and is not up-to-date.

That's due to branching off. The changelog would always be incomplete, therefore each stable branch carries the changelog info for its version only.

**Comment by SimJoSt** [comment]
Thanks for the explanation. I will check the branches in the future for the changelog details.
It's still confusing, that it's not so much off a log, as the history is missing.
