### ISSUE TITLE
impersonate logs out the admin

### ISSUE THREAD

**Issue by punkyard** [nextcloud/impersonate#225]
hi
after logging out of the impersonated account, the admin is also logged off, and the main logging page is displayed. which ruins the purpose of this app ^^

This is on AiO 6 docker version, NC 26.0.2, debian 11
on macos 10.15.7 with safari, brave and epic browsers

thank you for your concern on this topic

**Comment by blizzz** [comment]
do you limit the app to groups like https://github.com/nextcloud/impersonate/issues/133#issuecomment-1576670862 ? If so, that would be the culprit.

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
