### ISSUE TITLE
"Error loading message template: " 404 error trying to impersonate, Nextcloud 27

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/impersonate#243]
Hello and thanks for all the work !

On Nextcloud 27.1.4 and Impersonate 1.14.0
When clicking on Impersonate user, I get this message. 
Try on Firefox and Chromium
Console indicate 404 page and no log on `admin/logging`

![image](https://github.com/nextcloud/impersonate/assets/9005817/2324f37e-76a4-4a66-92db-d41726f83d5b)

Thanks for your help !

**Comment by blizzz** [comment]
@quentinDupont Thank you for reporting.

Against which URL do you see the 404 happening? Is there anything unusual about the user id?

**Comment by quentinDupont** [comment]
> @quentinDupont Thank you for reporting.
> 
> Against which URL do you see the 404 happening? Is there anything unusual about the user id?

![image](https://github.com/nextcloud/impersonate/assets/9005817/2883a7b3-6e04-45ad-923c-7a2ac2767e38)

Nope nothing unusual about this user. I try with all user and it doesn't work.

**Comment by blizzz** [comment]
This URL is not what I would expect to see. The 404 is correct there. 

As far as I a Middleware is using that template – but it would not create a url like that, this is not intended like this. What apps do you have enabled?

**Comment by quentinDupont** [comment]
> This URL is not what I would expect to see. The 404 is correct there.
> 
> As far as I a Middleware is using that template – but it would not create a url like that, this is not intended like this. What apps do you have enabled?

`Enabled:
  - activity: 2.19.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.2
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.4
  - groupfolders: 15.3.3
  - impersonate: 1.14.0
  - integration_excalidraw: 2.0.4
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.2.4
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.4.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.4
  - support: 1.10.0
  - systemtags: 1.17.0
  - tables: 0.6.5
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - duplicatefinder: 1.1.4 (installed 0.0.15)
  - encryption: 2.15.0
  - files_external: 1.19.0
  - integration_whiteboard: 0.0.14 (installed 0.0.14)
  - survey_client: 1.15.0 (installed 1.8.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)`

**Comment by blizzz** [comment]
Nothing uncommon I'd say.

- And the user who tried to impersonate is either in the admin group, or in of the groups configured to be allowed to impersonate?
- And the target user is not disabled?
- And the target user has logged in at least once before?

**Comment by quentinDupont** [comment]
- Yes, i use my account and i'm in admin group
![image](https://github.com/nextcloud/impersonate/assets/9005817/098994f4-cac6-469e-94f8-97780b423e61)
![image](https://github.com/nextcloud/impersonate/assets/9005817/8d6bc96d-1102-4626-9f29-0b4c147950f1)
- User is active and as already connected

**Comment by logan71f100** [comment]
i also have this same issue after updating to nextcloud 28

**Comment by logan71f100** [comment]
I wish I knew what setting, I have got many sites on this web server monkeying around with nginx settings all at once is bound to break something else haha

**Comment by blizzz** [comment]
@quentinDupont glad you found a solutions.

btw [there is more going on in nginx county](https://www.theregister.com/2024/02/16/freenginx_fork/).

**Comment by stellarpower** [comment]
Any update on what particular settings seem to have changed it @quentinDupont? Mine need tuning but since upgrading there are so many I haven't had time. Bit annoying they need constant attention when it's all within a pod. The file exists in my case so why it 404s, or if this really is the root cause, I'm not sure. Cheers.
