### ISSUE TITLE
Logout impersonated session returns not to previous user session

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/impersonate#31]
Releases
- nextcloud 13.0.0.14
- impersonate 1.0.2

Expected behaviour
- after logout from impersonated user, the session will return to the previous user session

Actual behaviour
- the session closes with completely logout. The main login screen is displayed
- but if the impersonated user also in group 'admin', logout works as expected

Perhaps I can provide some data (NC-log, browser console log, etc.). But I need some guidance what kind of informations are needed and how I can capture it.

**Comment by RailsViceRoads** [comment]
Tested with 
* nextcloud 13.0.1.1
* impersonate version 1.0.3. 
Same behaviour.

**Comment by RailsViceRoads** [comment]
Tested with

* nextcloud 13.0.1.1
* impersonate version 1.0.4.
* PHP 7.1.15
* mysql 5.6.19

Still the same behaviour.

**Comment by blizzz** [comment]
Hm, I never experiences issues with it. 

The browser log would be nice (on Firefox open it with Ctrl+Shift+K, then do the logout) and the nextcloud.log from your data folder.

**Comment by Dave-REBL** [comment]
Same issue noted on:

- Nextcloud 12.0.6 running on Ubuntu 16.04
- Impersonate app 1.0.4

**nextcloud.log**
`{"reqId":"73fBjIWZ7FTddjVdtrJR","level":1,"time":"2018-04-20 02:54:10","remoteAddr":"22.16.142.68","user":"--","app":"admin_audit","method":"POST","url":"\/login","message":"Login attempt: \"nc_admin\"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.6.1"}`

`{"reqId":"73fBjIWZ7FTddjVdtrJR","level":1,"time":"2018-04-20 02:54:10","remoteAddr":"22.16.142.68","user":"nc_admin","app":"admin_audit","method":"POST","url":"\/login","message":"Login successful: \"nc_admin\"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.6.1"}`

`{"reqId":"rIR6D8s3aiIHGz9x0I1o","level":2,"time":"2018-04-20 02:54:44","remoteAddr":"22.16.142.68","user":"nc_admin","app":"impersonate","method":"POST","url":"\/apps\/impersonate\/user","message":"User nc_admin trying to impersonate user nc_user","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.6.1"}`

`{"reqId":"rIR6D8s3aiIHGz9x0I1o","level":2,"time":"2018-04-20 02:54:44","remoteAddr":"22.16.142.68","user":"nc_admin","app":"impersonate","method":"POST","url":"\/apps\/impersonate\/user","message":"Changing to user nc_user","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.6.1"}`

`{"reqId":"OLv8voWh9b6gTSVeHsfZ","level":1,"time":"2018-04-20 02:59:36","remoteAddr":"22.16.142.68","user":"nc_user","app":"admin_audit","method":"GET","url":"\/logout?requesttoken=TIGaYqjmMNBEf4BanKqsOi%2B2%2BETukOxIlsXtUaUZR\/E%3D%3AfbTzDuvQeoAKGbBi%2BczZeX7bjxeJ1bgawJa3HpxwLoE%3D","message":"Logout occurred","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.6.1"}`

**Comment by blizzz** [comment]
Still cannot reproduce it, neither on Firefox nor on chromium-based Falkon.

The log does not show anything wrong, and also the involved logic is not that complicated. 

Is it a specifc app from where you cannot log out, or is it independent from it? Esssentially, does it work with files?

**Comment by Dave-REBL** [comment]
@blizzz 

Reproduced on Firefox browser. The Impersonate app works as expected other than what was explained in the originating post: when I log out of the impersonated (non-admin) user session I return to the Nextcloud login screen. I expected to return to the admin user session where I initiated the impersonate user session.

**Comment by GHMR** [comment]
@blizzz I was able to reproduce this bug by limiting this app to a group of users. The impersonated user was not member of the group.

**Comment by RailsViceRoads** [comment]
The issue is not browser spezific. I have testet with IE 11, Chrome 66.0 and FF 59.0.2. and all shows the same behaviour.

But I suspect the problem occurs allready by switching to the impersonated user, because:
- If I impersonate an user with administrator rights, I get a message in the header line
![grafik](https://user-images.githubusercontent.com/36618192/39188513-46bb7f36-47d0-11e8-92d3-4aa4edae1236.png)
- If I logout from this accout, all works as expected
- If I impersonate an user without admin rights, I get also no message on the top.
![grafik](https://user-images.githubusercontent.com/36618192/39188683-a92033b0-47d0-11e8-8c51-ba94cdb55bb8.png)
- in this case, logout will resume on main login screen.

**Comment by blizzz** [comment]
@GHMR 

Did I understood correctly, should this setup reproduce the observed behaviour?

![screenshot_20180425_234302](https://user-images.githubusercontent.com/2184312/39274480-661ff574-48e2-11e8-974c-a05d27f55754.png)

* Impersonating is enable for group "Sleeps At Night"
* I login as "molly"
* I impersonate as "melinda"
* I log out

I am ending up again in molly's session.

**Comment by RailsViceRoads** [comment]
@blizzz 
No, I suspect it means the Impersonate-App himself is limited to a group. 
Here are the settings on my own server, Usermenue (admin) --> +Apps

![grafik](https://user-images.githubusercontent.com/36618192/39319027-1c3f5578-4980-11e8-90e5-fef5beacd686.png)

**Comment by GHMR** [comment]
@blizzz @RailsViceRoads 
To be honest, I don't see the differences of your two tests.
But yes @blizzz, I think your setup should have reproduced the issue. I just used a different group than you did. I used the group admin to test it.

My test was like this:
- two users
- user: admin (member of group admin)
- user: max (member of group users)
- App 'impersonate' is limited to group admin
- login as admin
- open user management and impersonate as max
- logout as max ended up at the login screen of nextcloud

**Comment by blizzz** [comment]
> No, I suspect it means the Impersonate-App himself is limited to a group.
Here are the settings on my own server, Usermenue (admin) --> +Apps

That's wont work. The impersonate app won't be loaded for users outside of those groups and this includes users to be impersonated! Use the config option in Admin Settings → Additional instead for control who is allowed to impersonate.

**Comment by blizzz** [comment]
@GHMR to be sure, you didn't limit the app to groups on the apps page as @RailsViceRoads  did?

**Comment by blizzz** [comment]
Actually I'd rather check for a way to remove the possibility on the apps page. This way it would be too confusing.

**Comment by punkyard** [comment]
Hi
I read somewhere that this was fixed, but it's still not.. after each update, this bug is back on track ^^

>> After login out of the impersonated account with the NC admin user, the main login screen is displayed: admin is logged out too. So, admin has to login after each impersonification, which slows down the workflow.

On NC AiO 5.2.2
NC 26.0.2
Impersonate app 1.13.1

fingers crossed
have a good day

**Comment by blizzz** [comment]
It was https://github.com/nextcloud/impersonate/issues/133, I did not realize this old issue is still open. Will close it was well, @punkyard please follow up in #133. Try a hard refresh first, please also name your browser and check the browser console for errors.
