### ISSUE TITLE
Other Apps Don't Get Notified of Impersonate

### ISSUE THREAD

**Issue by TheCuteFoxxy** [nextcloud/impersonate#310]
As specified in #179 and #180 

As of the current version of Nextcloud (29.0.2) and Imperonate (1.16.0). Other apps aren't observing the impersonation of a user.

For example, Snappymail uses the emitted event to logout the admin in order to access the impersonated user's email.

If this is perhaps an issue with the apps rather than impersonate, than I can open an issue with them instead :)

**Comment by blizzz** [comment]
> If this is perhaps an issue with the apps rather than impersonate, than I can open an issue with them instead :)

Yes! Impersonate can only dispatch such Events, but listening or reacting towards them is task of potential consumers i.e. apps. So the request should be brought up with the relevant apps.
