### ISSUE TITLE
Move impersonate-button into dropdown with "disable" and "delete" user

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/impersonate#4]
https://github.com/nextcloud/server/pull/1234 will introduce this dropdown menu for every user, where you can select to disable or to delete a user. This menu is where the impersonate button should be placed 🙈

@nextcloud/designers

**Comment by jancborchardt** [comment]
Damn right @MariusBluem! :) Really good design proposals lately :tada:

**Comment by nickvergessen** [comment]
*unsubscribing*

**Comment by jancborchardt** [comment]
@nickvergessen no need to leave these comments.

**Comment by jancborchardt** [comment]
Thanks a lot @prodingerd! :) Further Javascript contributions are very welcome!
