### ISSUE TITLE
Impersonate and Encryption question

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/impersonate#48]
If a Nextcloud instance is using encryption, should it still be possible to see an impersonated users files?  I ask because I saw this on the app store page: 

> This app is not compatible with instances that have encryption enabled.

On my server, I have encryption but impersonate still allows me to see the contents of an impersonated users files.  Is this by design?

**Comment by blizzz** [comment]
Perhaps they were not encrypted, yet? Otherwise it would not be possible.

**Comment by aproposnix** [comment]
Just following up on this. The issue can be closed.  It was my misunderstanding of how the 0knowledge implementation worked. 

I was able to create an encrypted folder which could NOT be opened when using impersonate.
