### ISSUE TITLE
Problem with creating an app password as an impersonated user

### ISSUE THREAD

**Issue by stinch** [nextcloud/impersonate#51]
1) login as an admin user, "adam" for example
2) impersonate a user, "bob" for example
3) Settings > Security 
4) Enter an app name, "test" for example
5) click "Create new app password"

Expected result: the displayed credentials have a username of the impersonated user bob
Actual result: the displayed credentials have a username of the original user adam
See the attached screenshot.
![nextcloud-impersonate-issue](https://user-images.githubusercontent.com/10169315/43101705-f94017ea-8e96-11e8-85bc-0c31c24d29ed.png)

More significantly, the new app password does not work for a login as the impersonated user bob.

**Comment by stinch** [comment]
Nextcloud 13, Impersonate 1.0.4
This is a duplicate of issue #34 - sorry for not checking for duplicates before submitting.

**Comment by blizzz** [comment]
closing as dup
