### ISSUE TITLE
Impersonate aktion not visible in usermenu 14.0.0 Beta 3

### ISSUE THREAD

**Issue by bekl101** [nextcloud/impersonate#55]
App is shown as active in app overview, but no action visible in usermenu.
Neither in 3dot menu nor in user overwiew.
impersionate 1.1.0

**Comment by bekl101** [comment]
found same issue in closed records. Hope will be fixed in beta4
sorry for posting again.

**Comment by blizzz** [comment]
@bekl101 impersonate 1.1.0 was shipped with the fix and works fine here. Perhaps the browser cache?
