### ISSUE TITLE
Not working with Nextcloud 15 RC1

### ISSUE THREAD

**Issue by cabaretboy** [nextcloud/impersonate#64]
I tried changing the max version in the info.xml file to 15, but it appears that there is more work needed to make this compatible. It's a great tool and I hope it can be updated!

**Comment by blizzz** [comment]
Thanks for the feedback. Mind telling us what exactly is not working?

**Comment by cabaretboy** [comment]
After enabling the app, and going to the user list (from an admin account) there is no button or menu option to enable the impersonating. I've tried logging out and logging back in, and there's still no option.
The Impersonate where you can set the groups comes up in 'Additional settings', but basically there is nowhere to actually start the impersonation from.

**Comment by blizzz** [comment]
@cabaretboy  This should be fixed with https://github.com/nextcloud/impersonate/pull/63, once it it released.
