### ISSUE TITLE
mails should not be accessible by admin

### ISSUE THREAD

**Issue by wdfee** [nextcloud/impersonate#67]
1. When impersonating an user, the mail app should not be accessible for the admin. This is a data / privacy issue. The admin should not be able to read the users mails from his connected mail account. Maybe it could be possible to block the IMAP / SMTP server details for the admin user.

2. There should be a possibility for the user to mark files and folders as private. These files and folders should not be accessible by admins when impersonating user's account.

**Comment by mritzmann** [comment]
> This is a data / privacy issue

No, that's the point of the app...

**Comment by blizzz** [comment]
what @mritzmann says.

If files are sensitive, use end to end encryption (or some other form on en/de-crypting it on clients).

If mails are sensitive, use email encryption.
