### ISSUE TITLE
Impersonation with WebDAV

### ISSUE THREAD

**Issue by ShaunMaher** [nextcloud/impersonate#69]
Hi.

I'm trying to work around the (much discussed) issue that prevents the creation of App Passwords while impersonating.  I'm trying to impersonate all users, one at a time, to export their data for importation into a fresh new Nextcloud instance.

I didn't want this process to require resetting user passwords (LDAP/AD integrated).  I'd prefer to have something like rclone setup to copy the data from one WebDAV server to the other in an automated way, rather than needing to download user data using the WebUI.

So, would it be possible to extend the impersonate app to enable impersonation with WebDAV?  Maybe by presenting the desired user's name on the WebDAV URL like "https://nextcloud.fqdn/remote.php/webdav?impersonate=some.user".

Thoughts?

Cheers.
Shaun

**Comment by blizzz** [comment]
I don't think it is trivially done and might need changes on the server. Cannot even say it is possible.

For an export like that, you could simply rsync the data folder.
