### ISSUE TITLE
OCP\Files\NotFoundException when impersonating user without data

### ISSUE THREAD

**Issue by Rocreex** [nextcloud/impersonate#7]
Impersonating a user without data (i.e. if the user has never logged in), results in a OCP\Files\NotFoundException error, which means that Nextcloud only shows an "internal error" page, making it even impossible to log out. The only solution then is to delete the cookies in order to log in to your own account again.

**Comment by nitaish** [comment]
Instead of showing internal server error, it should show a message like you cannot impersonate an user which has not logged in yet or something similar. Internal Server Error makes one believe the product is buggy.

**Comment by Tsuroerusu** [comment]
I would like to second what @nitaish said, I just ran into this error, and I thought I had a permissions or a server-problem. But even more than that, why can it not be fixed so that I actually can impersonate a "never-logged-in-user". To me it would be useful for entering in the user's e-mail address, or preparing their account for use before they themselves log in without having to log in with their credentials.

**Comment by e-alfred** [comment]
The problem still exists with 12.0.3. I do not use any external authentication system.

I get this message:

`
{"reqId":"BnESYhlFd6HwDGG8UoyX","level":3,"time":"2017-10-02T14:19:31+00:00","remoteAddr":"1.1.1.1","user":"user","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.102 Safari\/537.36 Vivaldi\/1.94.971.8","version":"12.0.3.3"}`

**Comment by nickvergessen** [comment]
Fixed with #16
