### ISSUE TITLE
"Impersonate" not displayed in selected language (and should be changed to "Impersonate user")

### ISSUE THREAD

**Issue by j-ed** [nextcloud/impersonate#70]
## Expected behavior
All kind of text strings should be displayed in the selected language.

## Current behavior
The "**Impersonate**" category header under **Settings>Administration>Additional Settings** is not translated into German language and should be changed from **`Impersonate`** to **`Impersonate user`** ("**Benutzer nachahmen**") although a correct translation exists.

![20190402_nc_settings_additional_settings_impersonate_translation_of_-Impersonate-](https://user-images.githubusercontent.com/2572764/55458834-5b121580-55ee-11e9-9c83-7ccff919e0fd.png)

## Steps to reproduce
1. open the settings dialog
2. navigate to Administration>Additional Settings

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5
Impersonate app version: 1.2.0

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by blizzz** [comment]
It is translated for informal German, but not formal German.

**Comment by blizzz** [comment]
About the string itself I do not have hard feelings. It matches the app name. Changing it would need new translations, but that should be fine for a single string. Would you mind open a PR?

**Comment by j-ed** [comment]
@blizzz [**x**] done: https://github.com/nextcloud/impersonate/pull/71

**Comment by blizzz** [comment]
and merged, ty!
