### ISSUE TITLE
Does not work in NC16

### ISSUE THREAD

**Issue by agross** [nextcloud/impersonate#76]
I'm running 1.3.0 on NC 16 but the link next to the user's name does not show up. The app has been working before with NC 15.

**Comment by mgittelman** [comment]
Same issue here.

**Comment by agross** [comment]
It seems that the overflow menu (3 dots to the right of a user name column) is missing if the screen resolution is smaller than a certain value. I tested this again on screen and the Impersonate menu item shows up if the overflow menu is visible. 

![2019-05-04_20-48-43](https://user-images.githubusercontent.com/16245/57183494-0a702f80-6eae-11e9-8332-728b2b3ad64d.gif)

@mgittelman Can you verify?

**Comment by mgittelman** [comment]
Yes, same here.  They do actually appear to be showing up when the window is big enough.

I believe the screenshot for this plugin is misleading now, because it shows a separate column towards the left labeled impersonate, and that is no longer accurate.

https://apps.nextcloud.com/apps/impersonate

**Comment by agross** [comment]
The user menu issue has been reported: https://github.com/nextcloud/server/issues/15262

@mgittelman I'll close this. You may open another issue for the screenshot issue.
