### ISSUE TITLE
result.responseJSON is undefined

### ISSUE THREAD

**Issue by solracsf** [nextcloud/impersonate#83]
Some users i try to impersonate in my test instance return this in the browser (Firefox) console, as other works without problems.
```
TypeError: result.responseJSON is undefined @ impersonate.js:12:5
    impersonate https://example.com/apps/impersonate/js/impersonate.js?v=1504f9c4-9:12
    u https://example.com/core/js/dist/main.js?v=1504f9c4-9:39
    fireWith https://example.com/core/js/dist/main.js?v=1504f9c4-9:39
    k https://example.com/core/js/dist/main.js?v=1504f9c4-9:39
    t https://example.com/core/js/dist/main.js?v=1504f9c4-9:39
```

**Comment by blizzz** [comment]
Can you please describe what exactly happens?  What's the Nextcloud version, which backend is the target user from?

**Comment by acs-ferreira** [comment]
NC 16.0.4.1, all user backends are the same.
This happens once i click YES on the pop-up window.

![image](https://user-images.githubusercontent.com/12234510/65584885-de02a000-df81-11e9-99ad-459fdf321608.png)

Nothing happens, only the console error.
For other user, no error, and user is impersonated.

**Comment by blizzz** [comment]
You say it happens for some users. Is there any thing in common with those where it does not work (compared to those where it does)? They logged in before, right?

**Comment by acs-ferreira** [comment]
> They logged in before, right?
Can't answer that, is there any way on the interface to know it?

**Comment by blizzz** [comment]
on the users page, click on settings on the bottom left and check "Show last login".

**Comment by acs-ferreira** [comment]
You're right, users have never logged in.
Can the impersonate option be hidden on this specific case, or show a message like "User has never logged in, it can't be impersonated"?

**Comment by blizzz** [comment]
In that case, impersonating should not work at all actually and a warning be displayed. Already.

**Comment by blizzz** [comment]
Are those all users from the local backend or a different one?

**Comment by acs-ferreira** [comment]
Local only.

**Comment by solracsf** [comment]
Closing as fixed.
