### ISSUE TITLE
Are you sure you want to impersonate

### ISSUE THREAD

**Issue by kasumiru** [nextcloud/impersonate#90]
Need to add the normal disable method for disable "Are you sure you want to impersonate", or remove it completely, 'cause this feature is completely unnecessary, interferes with work.

**Comment by jpubb** [comment]
It is pretty serious to impersonate a user on the system.  A quick "Are you sure?" seems like a valid confirmation in case you meant to "Resend Welcome Email" (which currently is option above it... but who knows what future apps you will install that will add something above/below impersonate)

**Comment by blizzz** [comment]
I agree with @jpubb
