### ISSUE TITLE
Automation of Share Creation for All Users

### ISSUE THREAD

**Issue by sodiumchl** [nextcloud/impersonate#91]
This is not really an issue of this app. I just need some help.

I would like to create a _Public_ folder for each user and shared it to the _Everyone_ group. I could impersonate each user and click-click-click, but it would be great if this could be done with some automation, e.g., via the command line. In other words, can this app can be used as an `nc-sudo` command? After `nc-sudo`, I can then use the `ocs` API, I suppose. 

Or, is there an even better way to do this kind of automation?

Thank you very much!

**Comment by blizzz** [comment]
> This is not really an issue of this app. I just need some help.

Please ask in the [forums](https://help.nextcloud.com)
