### ISSUE TITLE
NC 19 RC2: Impersonate doesn't work

### ISSUE THREAD

**Issue by simonspa** [nextcloud/impersonate#96]
Apart from the fact that no proper NC19 version is available yet, the current version does not work with NC19.

### Steps:
* Enable untested app "impersonate"
* Go to users list, select user to impersonate
* Click on "yes" when asked if you want to impersonate
* You are logged in with your own user again, but in a "nested" impersonate session.

NC19 RC2,

**Comment by blizzz** [comment]
I fail to reproduce it.
